import fs from "node:fs";
import path from "node:path";
import readline from "node:readline";
import { fileURLToPath, pathToFileURL } from "node:url";

import { normalizeStoryPath } from "./story-path.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectDir = path.resolve(__dirname, "../..");
const sharedConfigPath = path.join(__dirname, "shared-config.mjs");
const generatedBlockStart = "// RECORDING_PRESELECTIONS_START";
const generatedBlockEnd = "// RECORDING_PRESELECTIONS_END";

function usage() {
  console.log(
    "Usage: node preselect-options.mjs <story> [--force|--reselect]\n" +
      "Examples:\n" +
      "  node preselect-options.mjs groupStory/1102 --force\n" +
      "  node preselect-options.mjs eventStory/10014005",
  );
}

function parseArguments(arguments_) {
  let rawStoryPath;
  let forceReselect = false;
  let autoFirst = false;
  let showHelp = false;

  for (const argument of arguments_) {
    if (argument === "--force" || argument === "--reselect") {
      forceReselect = true;
    } else if (argument === "--auto-first") {
      autoFirst = true;
    } else if (argument === "-h" || argument === "--help") {
      showHelp = true;
    } else if (argument.startsWith("-")) {
      throw new Error(`Unknown option: ${argument}`);
    } else if (rawStoryPath) {
      throw new Error("Only one story path can be specified");
    } else {
      rawStoryPath = argument;
    }
  }

  return { rawStoryPath, forceReselect, autoFirst, showHelp };
}

function parseOptions(text) {
  const options = [];
  for (const line of String(text || "").split("\n")) {
    const match = /^\s*\[n?s(\d{0,2})?\]\s*(.+?)\s*$/.exec(line);
    if (!match) {
      continue;
    }
    options.push({
      selectionGroup: Number(match[1] || "0"),
      text: match[2],
    });
  }
  return options;
}

function findOptionPages(content) {
  return content.flatMap((unit, storyIndex) => {
    const sourceOptions = parseOptions(unit.ScriptKr);
    if (sourceOptions.length === 0) {
      return [];
    }

    const translatedOptions = new Map(
      parseOptions(unit.TextCn).map(option => [
        option.selectionGroup,
        option.text,
      ]),
    );
    return [
      {
        storyIndex,
        options: sourceOptions.map(option => ({
          ...option,
          textCn: translatedOptions.get(option.selectionGroup) || option.text,
        })),
      },
    ];
  });
}

async function readAllPreSelections() {
  const configUrl = pathToFileURL(sharedConfigPath);
  configUrl.searchParams.set("cacheBust", String(Date.now()));
  const { storyPreSelections } = await import(configUrl.href);
  return new Map(storyPreSelections || []);
}

function renderGeneratedBlock(allSelections) {
  const entries = [...allSelections.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(
      ([storyPath, selections]) =>
        `  [${JSON.stringify(storyPath)}, ${JSON.stringify(selections)}],`,
    )
    .join("\n");

  return `${generatedBlockStart}
// Generated by preselect-options.mjs. storyIndex is the zero-based content index.
export const storyPreSelections = new Map([
${entries}
]);
${generatedBlockEnd}`;
}

function writeAllPreSelections(allSelections) {
  const generatedBlock = renderGeneratedBlock(allSelections);
  const sharedConfig = fs.readFileSync(sharedConfigPath, "utf8");
  const blockStart = sharedConfig.indexOf(generatedBlockStart);
  const blockEnd = sharedConfig.indexOf(generatedBlockEnd);

  let updatedConfig;
  if (blockStart === -1 && blockEnd === -1) {
    updatedConfig = `${sharedConfig.trimEnd()}\n\n${generatedBlock}\n`;
  } else if (blockStart !== -1 && blockEnd !== -1 && blockEnd > blockStart) {
    updatedConfig =
      sharedConfig.slice(0, blockStart) +
      generatedBlock +
      sharedConfig.slice(blockEnd + generatedBlockEnd.length);
  } else {
    throw new Error(
      "shared-config.mjs has an incomplete recording preselection block",
    );
  }

  fs.writeFileSync(sharedConfigPath, updatedConfig, "utf8");
}

function hasSelection(page, selectionGroup) {
  return page.options.some(
    option => option.selectionGroup === selectionGroup,
  );
}

async function main() {
  const { rawStoryPath, forceReselect, autoFirst, showHelp } = parseArguments(
    process.argv.slice(2),
  );
  if (showHelp) {
    usage();
    return;
  }
  if (!rawStoryPath) {
    usage();
    process.exitCode = 1;
    return;
  }

  const { storyPath, type, directoryId, id } =
    normalizeStoryPath(rawStoryPath);
  const storyJsonPath = directoryId
    ? path.join(
      projectDir,
      "public/story",
      type,
      directoryId,
      `${id}.json`,
    )
    : path.join(projectDir, "public/story", type, `${id}.json`);
  if (!fs.existsSync(storyJsonPath)) {
    throw new Error(`Story file not found: ${storyJsonPath}`);
  }

  const storyJson = JSON.parse(fs.readFileSync(storyJsonPath, "utf8"));
  const optionPages = findOptionPages(storyJson.content || []);
  if (optionPages.length === 0) {
    console.log(`No selection pages found in ${storyPath}.`);
    return;
  }

  console.log(
    `Found ${optionPages.length} selection page(s) in ${storyPath}.`,
  );
  if (forceReselect) {
    console.log("Forcing re-selection of all multi-option pages.");
  }
  const allSelections = await readAllPreSelections();
  const existingSelections = new Map(
    (allSelections.get(storyPath) || []).map(selection => [
      selection.storyIndex,
      selection.selectionGroup,
    ]),
  );
  const selected = [];
  const readlineInterface = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  const question = query =>
    new Promise(resolve => readlineInterface.question(query, resolve));

  try {
    for (const [pageNumber, page] of optionPages.entries()) {
      const existingSelection = existingSelections.get(page.storyIndex);
      console.log(
        `\nSelection page ${pageNumber + 1} (content index ${page.storyIndex}):`,
      );
      for (const option of page.options) {
        console.log(`  [${option.selectionGroup}] ${option.textCn}`);
      }

      let selectionGroup;
      if (page.options.length === 1) {
        selectionGroup = page.options[0].selectionGroup;
        console.log(`Auto-selected the only option: [${selectionGroup}]`);
      } else if (autoFirst) {
        selectionGroup = page.options[0].selectionGroup;
        console.log(`Auto-selected the first option via --auto-first: [${selectionGroup}]`);
      } else if (
        !forceReselect &&
        existingSelection !== undefined &&
        hasSelection(page, existingSelection)
      ) {
        selectionGroup = existingSelection;
        console.log(`Using saved option: [${selectionGroup}]`);
      } else {
        while (selectionGroup === undefined) {
          const answer = await question(
            "Which option should recording auto-select? " +
              "(enter SelectionGroup): ",
          );
          const candidate = Number(answer.trim());
          if (Number.isInteger(candidate) && hasSelection(page, candidate)) {
            selectionGroup = candidate;
          } else {
            console.log("Invalid selection; please try again.");
          }
        }
      }

      selected.push({
        storyIndex: page.storyIndex,
        selectionGroup,
      });
    }
  } finally {
    readlineInterface.close();
  }

  const previous = allSelections.get(storyPath);
  if (JSON.stringify(previous) === JSON.stringify(selected)) {
    console.log(`\nPre-selections for ${storyPath} are already up to date.`);
    return;
  }

  allSelections.set(storyPath, selected);
  writeAllPreSelections(allSelections);
  console.log(
    `\nSaved ${selected.length} pre-selection(s) for ${storyPath} to ` +
      "shared-config.mjs.",
  );
}

main().catch(error => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
