export function normalizeTextJpVoice(value) {
  let text = String(value ?? "");
  let previous;

  // TTS must never read parenthetical annotations, including abbreviations
  // such as "(SNP)" and full-width Japanese stage directions.
  do {
    previous = text;
    text = text.replace(/\([^()]*\)|（[^（）]*）/gu, "");
  } while (text !== previous);

  return text
    .replace(/[ \t]+(?=\n|$)/gu, "")
    .replace(/[ \t]{2,}/gu, " ")
    .trim();
}

export const textJpVoiceOverrides = new Map([
  [
    "1102:4",
    {
      expectedScriptKr:
        "5;이즈미;08;뭐어어? 트뤼플? 나도 먹고싶었는데에에에!\n#5;a\n#5;em;[반응]",
      expectedTextJp: "えええっ！？トリュフ？？私も食べたかったのにいいい！",
      textJpVoice:
        "[surprised]えええっ！？[screaming]トリュフ？？[pity]私も食べたかったのに！",
    },
  ],
  [
    "1102:11",
    {
      expectedScriptKr:
        "5;이즈미;04;(쾅쾅쾅쾅-!!) 야 이 놈들아!! 니들만 맛있는 거 먹기냐!! #n우리도 나눠줘! 으애애애애-!!\n#5;shake",
      expectedTextJp:
        "（ドンドンドンドン！！！）鬼！悪魔！あなたたちだけ美味しいの食べて！\n食べ物の恨みは恐ろしいんだぞ！！\n私にもちょうだいよおおお！うああああん！！",
      textJpVoice:
        "[screaming]鬼！悪魔！あなたたちだけ美味しいの食べて！\n[angry]食べ物の恨みは恐ろしいんだぞ！！\n[screaming]私にもちょうだいよおお！うああああん！！",
    },
  ],
  [
    "1102:56",
    {
      expectedScriptKr:
        "5;히나;99;누가 학교 수영장에서 알몸으로 수영하고 있다는 신고만으로 선생님을 구금한 건…… #n확실히 내가 좀 성급했던 거 같긴 한데…….\n#5;m4",
      expectedTextJp:
        "学校のプールで裸で泳いでいるっていう通報を受けただけで先生を拘束したのは……\n実際私の早とちりだったみたい、だけど……。",
      textJpVoice:
        "[hesitant] 学校のプールで裸で泳いでいるっていう通報を受けただけで先生を拘束したのは……\n[sorry] 実際私の早とちりだったみたい、だけど……。",
    },
  ],
  [
    "1102:65",
    {
      expectedScriptKr:
        "3;히나;15;변명은 지옥에서 듣지.\n#fontsize;80\n#3;closeup",
      expectedTextJp: "言い訳は地獄で聞くから。",
      textJpVoice: "[angry]言い訳は地獄で聞くから。",
    },
  ],
]);

function validateTextJpVoiceOverride(key, override, unit) {
  if (unit.TextJp !== override.expectedTextJp) {
    throw new Error(
      `TextJpVoice override ${key} TextJp mismatch; ` +
        "update shared-config.mjs manually",
    );
  }
  if (unit.ScriptKr !== override.expectedScriptKr) {
    throw new Error(
      `TextJpVoice override ${key} ScriptKr mismatch; ` +
        "update shared-config.mjs manually",
    );
  }
}

export function applyStoryTextJpVoiceOverrides(storyId, content) {
  const lockedIndices = new Set();
  const prefix = `${storyId}:`;

  for (const [key, override] of textJpVoiceOverrides) {
    if (!key.startsWith(prefix)) {
      continue;
    }

    const matches = [];
    for (let index = 0; index < content.length; index++) {
      const unit = content[index];
      if (
        unit.TextJp === override.expectedTextJp &&
        unit.ScriptKr === override.expectedScriptKr
      ) {
        matches.push(index);
      }
    }
    if (matches.length !== 1) {
      throw new Error(
        `TextJpVoice override ${key} expected exactly one exact story match, ` +
          `found ${matches.length}; update shared-config.mjs manually`,
      );
    }

    const index = matches[0];
    const unit = content[index];
    validateTextJpVoiceOverride(key, override, unit);
    unit.TextJpVoice = normalizeTextJpVoice(override.textJpVoice);
    if (!unit.TextJpVoice) {
      unit.VoiceJp = "";
    }
    lockedIndices.add(index);
  }

  return lockedIndices;
}

export const voiceTagExamples = [
  "pause",
  "emphasis",
  "laughing",
  "inhale",
  "chuckle",
  "tsk",
  "singing",
  "excited",
  "laughing tone",
  "interrupting",
  "chuckling",
  "excited tone",
  "volume up",
  "echo",
  "angry",
  "low volume",
  "sigh",
  "soft sigh",
  "low voice",
  "whisper",
  "screaming",
  "shouting",
  "loud",
  "surprised",
  "confused",
  "hesitant",
  "embarrassed",
  "teasing",
  "playful",
  "smug",
  "deadpan",
  "sarcastic",
  "elegant tone",
  "gentle",
  "nervous",
  "worried",
  "relieved",
  "determined",
  "serious",
  "panicked",
  "frustrated",
  "annoyed",
  "awkward laugh",
  "soft laugh",
  "mischievous",
  "proud",
  "dramatic",
  "matter-of-fact",
  "short pause",
  "exhale",
  "delight",
  "panting",
  "audience laughter",
  "with strong accent",
  "volume down",
  "clearing throat",
  "sad",
  "moaning",
  "shocked",
  "pity",
  "sorry",
  "whisper in small voice",
  "professional broadcast tone",
  "pitch up",
];

/* eslint-disable max-len -- generated recording selections */
// RECORDING_PRESELECTIONS_START
// Generated by preselect-options.mjs. storyIndex is the zero-based content index.
export const storyPreSelections = new Map([
  ["eventStory/10014005", [{"storyIndex":7,"selectionGroup":2},{"storyIndex":18,"selectionGroup":3},{"storyIndex":30,"selectionGroup":5}]],
  ["eventStory/10014010", [{"storyIndex":1,"selectionGroup":2},{"storyIndex":10,"selectionGroup":3},{"storyIndex":19,"selectionGroup":5},{"storyIndex":36,"selectionGroup":7}]],
  ["eventStory/10014015", [{"storyIndex":32,"selectionGroup":2},{"storyIndex":62,"selectionGroup":3}]],
  ["eventStory/10014020", [{"storyIndex":7,"selectionGroup":2},{"storyIndex":29,"selectionGroup":0},{"storyIndex":50,"selectionGroup":4},{"storyIndex":67,"selectionGroup":0},{"storyIndex":93,"selectionGroup":5},{"storyIndex":97,"selectionGroup":7},{"storyIndex":104,"selectionGroup":0},{"storyIndex":122,"selectionGroup":10}]],
  ["eventStory/10014025", [{"storyIndex":30,"selectionGroup":2},{"storyIndex":34,"selectionGroup":3},{"storyIndex":39,"selectionGroup":5},{"storyIndex":62,"selectionGroup":7},{"storyIndex":102,"selectionGroup":9},{"storyIndex":112,"selectionGroup":11},{"storyIndex":117,"selectionGroup":13},{"storyIndex":129,"selectionGroup":0},{"storyIndex":131,"selectionGroup":0}]],
  ["eventStory/10014030", [{"storyIndex":5,"selectionGroup":0},{"storyIndex":9,"selectionGroup":2},{"storyIndex":33,"selectionGroup":3},{"storyIndex":38,"selectionGroup":5},{"storyIndex":61,"selectionGroup":7},{"storyIndex":76,"selectionGroup":9},{"storyIndex":87,"selectionGroup":0},{"storyIndex":89,"selectionGroup":11}]],
  ["eventStory/10014035", [{"storyIndex":3,"selectionGroup":2},{"storyIndex":27,"selectionGroup":3},{"storyIndex":38,"selectionGroup":5},{"storyIndex":48,"selectionGroup":7},{"storyIndex":61,"selectionGroup":9},{"storyIndex":65,"selectionGroup":11},{"storyIndex":82,"selectionGroup":13}]],
  ["eventStory/10014040", [{"storyIndex":18,"selectionGroup":0},{"storyIndex":33,"selectionGroup":3},{"storyIndex":46,"selectionGroup":6},{"storyIndex":58,"selectionGroup":0},{"storyIndex":87,"selectionGroup":9},{"storyIndex":137,"selectionGroup":13}]],
  ["eventStory/10014045", [{"storyIndex":19,"selectionGroup":1},{"storyIndex":74,"selectionGroup":0}]],
  ["eventStory/10014050", [{"storyIndex":3,"selectionGroup":1},{"storyIndex":14,"selectionGroup":3},{"storyIndex":35,"selectionGroup":0},{"storyIndex":43,"selectionGroup":5},{"storyIndex":53,"selectionGroup":7},{"storyIndex":74,"selectionGroup":9}]],
  ["eventStory/10014055", [{"storyIndex":16,"selectionGroup":2},{"storyIndex":22,"selectionGroup":4},{"storyIndex":33,"selectionGroup":5},{"storyIndex":44,"selectionGroup":7},{"storyIndex":61,"selectionGroup":0}]],
  ["eventStory/10014060", [{"storyIndex":13,"selectionGroup":1},{"storyIndex":34,"selectionGroup":3},{"storyIndex":40,"selectionGroup":0},{"storyIndex":42,"selectionGroup":5}]],
  ["eventStory/10014065", [{"storyIndex":5,"selectionGroup":1},{"storyIndex":27,"selectionGroup":4},{"storyIndex":55,"selectionGroup":5}]],
  ["eventStory/10014070", [{"storyIndex":69,"selectionGroup":1},{"storyIndex":132,"selectionGroup":3},{"storyIndex":137,"selectionGroup":5},{"storyIndex":159,"selectionGroup":7}]],
  ["eventStory/10014075", [{"storyIndex":21,"selectionGroup":1},{"storyIndex":54,"selectionGroup":3},{"storyIndex":88,"selectionGroup":5},{"storyIndex":112,"selectionGroup":7}]],
  ["eventStory/10014080", [{"storyIndex":6,"selectionGroup":1},{"storyIndex":12,"selectionGroup":3},{"storyIndex":28,"selectionGroup":5},{"storyIndex":82,"selectionGroup":8}]],
  ["eventStory/10014085", [{"storyIndex":30,"selectionGroup":2},{"storyIndex":37,"selectionGroup":3},{"storyIndex":58,"selectionGroup":5}]],
  ["groupStory/1102", [{"storyIndex":34,"selectionGroup":0},{"storyIndex":38,"selectionGroup":1},{"storyIndex":42,"selectionGroup":3},{"storyIndex":46,"selectionGroup":5},{"storyIndex":58,"selectionGroup":0},{"storyIndex":62,"selectionGroup":0}]],
]);
// RECORDING_PRESELECTIONS_END
/* eslint-enable max-len */
